branches:
  only:
    - master

language: node_js
node_js:
  - '14'
os: linux
dist: bionic

notifications:
  email:
    recipients:
      - raaed.kabir@gmail.com
    on_success: always

cache:
  npm: true
  directories:
    - node_modules

before_deploy:
  - npm run build

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $S3_BUCKET
  region: ap-southeast-1
  local_dir: dist
  edge: true